### ISSUE TITLE
Is login mandatory ?

### ISSUE THREAD

**Issue by wangjiahong** [nejckorasa/instagram-analyzer#3]
Hi, this is a very nice project.
I would like to access all the locations of an instagram account (account is public, not private), is login still mandatory? 

Thanks
@nejckorasa @uroshekic

**Comment by nejckorasa** [comment]
Hi @wangjiahong, thanks! Login is still mandatory, but it has been some time since the project was updated. I think Instagram has deprecated its old API, so this project might need to be upgraded with the new API. Feel free to open a PR!

#4 addresses possible upgrade of Instagram API
